on:
  push:
    branches: [ main ]
    
name: lambda trigger

jobs:
  trigger:
    name: trigger
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # give your aws_region
    
  
    - name: aws ec2 
      run: |
        sudo apt-get install awscli
   
    - name: installimg python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: installing boto3
      run: |
        sudo apt-get install -y python-boto
    - run: /usr/bin/python my_script.py start
      
     




        
 
