on:
  push:
    branches: [ main ]
 # schedule:
  #  - cron: "*/5 * * * *"
    
name: lambda trigger stop

jobs:
  trigger:
    name: trigger
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # give your aws_region
        
            
  
    - name: aws ec2 
      run: |
        sudo apt-get install awscli
   
    - run: | 
        #aws ec2 start-instances --instance-ids i-0c3dc20ba11f4efaf
        aws ec2 stop-instances --instance-ids `aws ec2 describe-instances --filters "Name=tag:Type,Values=Scheduled" --query 'Reservations[].Instances[].InstanceId' --output text`
    #- name: installimg python
